export const FETCH_ALL = "FETCH_ALL";
export const FETCH_FAIL = "FETCH_FAIL";

export const FETCH_PHONE = "FETCH_PHONE";

export const PHONE_DETAILS_REQUEST = "PHONE_DETAILS_REQUEST";
export const PHONE_DETAILS_SUCCESS = "PHONE_DETAILS_SUCCESS";
export const PHONE_DETAILS_FAIL = "PHONE_DETAILS_FAIL";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const CREATE_PHONE_REQUEST = "CREATE_PHONE_REQUEST";
export const CREATE_PHONE_SUCCESS = "CREATE_PHONE_SUCCESS";
export const CREATE_PHONE_FAIL = "CREATE_PHONE_FAIL";
export const CREATE_PHONE_RESET = "CREATE_PHONE_RESET";

export const DELETE_PHONE_REQUEST = "DELETE_PHONE_REQUEST";
export const DELETE_PHONE_SUCCESS = "DELETE_PHONE_SUCCESS";
export const DELETE_PHONE_FAIL = "DELETE_PHONE_FAIL";
export const DELETE_PHONE_RESET = "DELETE_PHONE_RESET";

export const UPDATE_PHONE_REQUEST = "UPDATE_PHONE_REQUEST";
export const UPDATE_PHONE_SUCCESS = "UPDATE_PHONE_SUCCESS";
export const UPDATE_PHONE_FAIL = "UPDATE_PHONE_FAIL";
export const UPDATE_PHONE_RESET = "UPDATE_PHONE_RESET";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
